spring:
  application:
    name: src-own-api-gateway

  threads:
    virtual:
      enabled: true

api-gateway:
  filter: "com.luigivis.srcownapigateway.filter.TestFilter"
  routes:
    - name: test
      to: https://api.restful-api.dev/
      from: /objects/**
      method: GET, POST

    - name: test1
      to: https://api.restful-api.dev/
      from: /objects

    - name: test2
      to: https://dog.ceo/
      from: /api/**

server:
  port: 4000